### ISSUE TITLE
On android, pressing trust in BadCertificateException doesn't work

### ISSUE THREAD

**Issue by gzqx** [bradyt/taskw-dart#14]
The same exact profile works on my iPhone, but on my android when pressing "trust" button nothing happens.
I am using the latest version installed from google play.

**Comment by bradyt** [comment]
Version 0.1.4 has a few changes that might be slightly useful in troubleshooting.

You can long press taskd.ca to remove it. That's not so relevant to your issue, except that currently it seems the taskd.ca isn't working, potentially a taskd.ca avoids the BadCertificateException. Still hoping we can fix that.

Also, if server.cert has been saved to storage, that is now indicated with an extra list item in configuration display. You can remove the server.cert by tapping it. That may be convenient for your troubleshooting.

Also the "Copy configuration to new profile" button was slightly broken for incomplete setups, and that should be fixed now.

I also added notes to wiki at <https://github.com/bradyt/taskw-dart/wiki/Troubleshooting-PEM-files>, derived from notes I noticed at Taskserver project.

When you have a chance, can you check if at least one of the following fails?

1. Can you validate the `server.cert`?
   - For example, `gnutls-cli <domain> ...` or `certtool --verify ...`.
2. Make sure the app's `taskd.ca` is the same as the `ca.cert` configured at server.
   - For example, by comparing SHA-1 displayed in app versus that shown with `certtool -i ...`.

If both of those indicate correct setup and you still see BadCertificateException before Trust button adds server.cert, I am hoping we can research this further.

I'm hoping to check these before the issue goes away if you are reconfiguring your setup or stop using this humble app.

**Comment by bradyt** [comment]
I'm not sure the interest above in discussing certs, and it seems the issue as originally filed is solved. Closing. Comments welcome.
