### ISSUE TITLE
Setup for Task server in windows

### ISSUE THREAD

**Issue by M-A-D-A-R-A** [bradyt/taskw-dart#20]
Hey, So I'm successfully able to run the flutter project, I want to configure on my own Task-Server on windows, I looked up in your "[WiKi](https://github.com/bradyt/taskw-dart/wiki/Draft-of-CONTRIBUTING.md#debugging)" and Im using WSL too but i could able to setup the server up and its server file on the flutter project. I tried using the [hosted Solution](https://freecinc.com/). It will be helpful if you could guide me through the setup for it.Thanks

**Comment by bradyt** [comment]
Greetings @M-A-D-A-R-A, thank you for trying out the project.

Can I interpret the question that you'd like to know how to connect the app to a Taskserver instance running locally on Windows?

If so, there seems to be a tangential mention of having tried to connect to a remote Taskserver, where you mention a hosted solution and link to FreeCinc. Perhaps you can document where you got stuck with that, and file a separate issue?

**Comment by bradyt** [comment]
Regarding running Taskserver on localhost, I just checked the steps outlined at https://github.com/bradyt/taskw-dart/wiki/Development on macOS. I'll try to describe what those steps do, and in the context of how I expect them to work on Windows.

In WSL with Debian (a version of GNU/Linux I found it easy to install taskd), in the `taskw-dart` project, I try the following:

```sh
> cd fixture
> make install # this installs an executable from `../taskc` called taskd-setup
> make setup # this sets up taskd with `TASKDDATA=./var/taskd`, and adds a `.taskrc` and `.task/*.pem` files to `../task/assets`
> make # this starts the taskd process with verbose logging to terminal
```

Then, in PowerShell, I would try the following:

```powershell
> cd task
> flutter run -d windows
```

Then within the app, with a new profile, go to the Taskserver Configuration screen, and click on the debugging button. That will automatically access the files from `./task/assets` mentioned above. At this point, we should now be able to connect to the running Taskserver process. The debugging icon/button is just there as a convenience for developers. You can also just use the normal file selection methods to select the files from `/path/to/taskw-dart/task/assets/`.

However, I'm getting an error when trying to run Dart 2.16.0 in WSL, so I'm hoping you have success with the above and don't run into issues running Dart in WSL.

**Comment by bradyt** [comment]
Okay, I was able to get this to work for me, so I'll add some notes.

Originally I was trying to access a Windows partition through VM software, and I was having difficulty getting Dart or WSL 2 or Docker to work there. So when I tried booting directly into the Windows partition, the situation seemed to improve.

I did end up using WSL 2, I'm not sure if that's necessary.

```
PS > wsl -l -v
  NAME      STATE           VERSION
* Debian    Running         2
```

I also realized, after a few awkward to read error messages, that the above `make` commands I describe above, require that you have the following software installed on the GNU/Linux session:

- Dart
  - (check `readlink -f $(which dart)` to make sure you're not using the Dart from your Windows C drive, as that caused issues for me)
- make
- taskd
- taskwarrior

I plan to update wiki with these details.

**Comment by M-A-D-A-R-A** [comment]
I just gave my laptop, for service today itself (replying to this thread via mail xD). I will try this solution as soon as i got my laptop back. Thank you so much for responding once again.

**Comment by bradyt** [comment]
Sounds good. So far, the thread has been useful in motivating me to update notes on this.

I've renamed the Development wiki notes to [Running Taskserver locally](https://github.com/bradyt/taskw-dart/wiki/Running-Taskserver-locally), and expanded the notes with the above.

**Comment by bradyt** [comment]
@M-A-D-A-R-A can I get an estimate on how long to leave this issue open? Technically I think I've updated the documentation to solve the issue, but didn't want to close the issue in case you were still planning on running taskd on Windows.

**Comment by M-A-D-A-R-A** [comment]
Yeah i am trying to run the taskd on windows, but yeah will look up to your updated documentation to follow the steps.You can close the issue. THANK YOU VERY MUCH !

**Comment by bradyt** [comment]
Okay, I appreciate you pointing out the missing docs. Let me know if you find something that shows the issue to be reopened. Closing.
