### ISSUE TITLE
ios: Cannot edit taskd.server property when configuring taskd

### ISSUE THREAD

**Issue by neurosnap** [bradyt/taskw-dart#26]
Greetings!  I'm trying to set up taskserver but for some reason I cannot edit the `taskd.server` property on iOS.  I was expected to see a text input that I could type the name of the server.

**Comment by bradyt** [comment]
Does the following help?

> To set `taskd.server` and `taskd.credentials`, press "Select TASKRC" and add a file that contains those settings.
>
> -- https://github.com/bradyt/taskw-dart/wiki/Usage#select-taskrc-taskdservercredentials

I would recommend a filename like `taskrc.txt`, then include the lines like you would see in your `TASKRC` file. As of version 0.2.6, the rest of your `TASKRC` would be ignored.

**Comment by neurosnap** [comment]
That worked. Thanks!
