### ISSUE TITLE
Won't hide tasks with wait date set

### ISSUE THREAD

**Issue by laenglea** [bradyt/taskw-dart#30]
Version: latest IOS one

Waiting tasks are always shown

example:
task add make party wait:2025-12-12

would hide till end of 2025 and is only visible under

task waiting.

In the ios app it's visible from today.

**Comment by bradyt** [comment]
Here's the relevant part of the changelog for version 0.2.8, on App Store:

```
- Fix: Pending filter should filter tasks with wait field set to future date
- Wait field is now displayed in task list item, and can be sorted on
```

However, while trying to be conservative in maintenance, I've nevertheless somehow lost the icon in the build. I've opened a separate issue for visibility and anyone wanting to track:

- https://github.com/bradyt/taskw-dart/issues/31

**Comment by laenglea** [comment]
I just tried it. Tasks are hiding now - thank you so much.
