### ISSUE TITLE
cant configure taskserver

### ISSUE THREAD

**Issue by gitjax** [bradyt/taskw-dart#40]
Hey,
when I tap "configure taskserver" and then "select taskrc", the files app opens up, but everything is just grayed out and I can't select any file. Tried changing extensions, no go.  Same thing for "taskd.key", "taskd.ca" etc.  I know for a fact this worked in an earlier version.

**Comment by bradyt** [comment]
Thank you for the report, will investigate. Can you confirm you installed `task add` on iOS's App Store?

**Comment by gitjax** [comment]
Yes I installed from the App Store

**Comment by bradyt** [comment]
I believe version 0.2.11 is now available on App Store, and may fix the issue.

**Comment by gitjax** [comment]
Yes! Now it works! Thanks a bunch for a great app!

**Comment by gitjax** [comment]
Closing
